# Generated by Django 3.1.5 on 2021-04-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orderapp', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='upload_at',
            new_name='update_at',
        ),
    ]
